IF DB_ID('Kursova_NVBD_V8_OLTP') IS NOT NULL
BEGIN
    ALTER DATABASE Kursova_NVBD_V8_OLTP SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Kursova_NVBD_V8_OLTP;
END
GO

CREATE DATABASE Kursova_NVBD_V8_OLTP;
GO
